
def print_problem():
    print("Each new term in the Fibonacci sequence is generated by adding the previous two terms. " +
          "By starting with 1 and 2, the first 10 terms will be:\n" +
          "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n" +
          "By considering the terms in the Fibonacci sequence whose values do not exceed four million, " +
          "find the sum of the even-valued terms.")


def create_fibonacci_list():
    fibonacci_list = [1, 2]
    first = fibonacci_list[0]
    second = fibonacci_list[1]
    while True:
        new_number = first + second
        if new_number >= 4000000:
            break
        fibonacci_list.append(new_number)
        first = second
        second = new_number
    return fibonacci_list


def calculate(number_list):
    result = 0
    for number in number_list:
        if number % 2 == 0:
            result = result + number
    return result


def get_answer():
    fibonacci_list = create_fibonacci_list()
    return calculate(fibonacci_list)


print_problem()
print('Answer: ', get_answer())
